export default [
    {
        0: 'A',
        1: 'Accurate Audio',
        2: 'Accustic Arts',
        3: 'Acer',
        4: 'Acoustic Energy',
        5: 'Acoustic Revive',
        6: 'Acoustic Solid',
    },
    {
        0: 'B',
        1: 'B&W',
        2: 'Bang & Olufsen',
        3: 'Barco',
        4: 'Barefoot Sound',
        5: 'BC Acoustique',
        6: 'BDI'
    },
    {
        0: 'C',
        1: 'Cabasse',
        2: 'Cambridge Audio',
        3: 'Campfire Audio',
        4: 'Canon',
        5: 'Canton',
        6: 'Cardas',
    },
    {
        0: 'D',
        1: 'Dali',
        2: 'Datasat',
        3: 'Davis',
        4: 'Definitive Technology',
        5: 'Dell',
        6: 'Denon',
    },
    {
        0: 'E',
        1: 'E-MU',
        2: 'EAR Yoshino',
        3: 'Earthquake',
        4: 'Ecosse',
        5: 'EgglestonWorks',
        6: 'Elac',
    },
    {
        0: 'F',
        1: 'Fender',
        2: 'Fibaro',
        3: 'FIIO',
        4: 'FilmoScope',
        5: 'Finite Elemente',
        6: 'Fischer Audio',
    },
    {
        0: 'G',
        1: 'Gamut',
        2: 'Gauder Akustic',
        3: 'Genelec',
        4: 'GigaWatt',
        5: 'Goertz',
        6: 'Gold Note',
    },
    {
        0: 'H',
        1: 'Hamilex',
        2: 'Hannl Vinyl Care',
        3: 'Hannspree',
        4: 'Harbeth',
        5: 'Harman Kardon',
        6: 'Harman Kardon Multimedia',
    },
    {
        0: 'I',
        1: 'iBasso',
        2: 'Ibiza',
        3: 'ICE',
        4: 'iEast',
        5: 'IFI',
        6: 'Imerge',
    },
    {
        0: 'J',
        1: 'Jadis',
        2: 'JAMO',
        3: 'Jarre',
        4: 'JBL',
        5: 'Jbl Multimedia',
        6: 'JBL Pro',
    },
    {
        0: 'K',
        1: 'Kalista',
        2: 'KEF',
        3: 'Kennerton',
        4: 'Kenwood',
        5: 'Kimber Kable',
        6: 'Kinera',
    },
    {
        0: 'L',
        1: 'L.K.S. Audio',
        2: 'Lars && Ivan',
        3: 'Lasmex',
        4: 'Lautsenn',
        5: 'Lector',
        6: 'Lehmannaudio',
    },
    {
        0: 'M',
        1: 'Mac Audio',
        2: 'Magico',
        3: 'Magnat',
        4: 'Magnum Dynalab',
        5: 'Manley',
        6: 'Marantz',
    },
    {
        0: 'N',
        1: 'NAD',
        2: 'Nagaoka',
        3: 'Naim',
        4: 'Nakamichi',
        5: 'Nativ',
        6: 'NBS',
    },
    {
        0: 'O',
        1: 'Octave',
        2: 'Oehlbach',
        3: 'Okki Nokki',
        4: 'Olive',
        5: 'OmniMount',
        6: 'Onkyo',
    },
    {
        0: 'P',
        1: 'Panasonic',
        2: 'Paradigm',
        3: 'Parasound',
        4: 'Partington',
        5: 'Pass Labs',
        6: 'Pathos',
    },
    {
        0: 'Q',
        1: 'Q Acoustics',
        2: 'QLS',
        3: 'QSC',
        4: 'Quad',
        5: 'Questyle',
    },
    {
        0: 'R',
        1: 'Radiotehnika',
        2: 'Radius',
        3: 'RBH',
        4: 'Real Cable',
        5: 'Rega',
        6: 'REL',
    },
    {
        0: 'S',
        1: 'S.M.S.L',
        2: 'SAEC',
        3: 'Samsung',
        4: 'Sanyo',
        5: 'Schnepel',
        6: 'Schroers & Schroers',
    },
    {
        0: 'T',
        1: 'T+A',
        2: 'T-Peos',
        3: 'Taga Harmony',
        4: 'Tannoy',
        5: 'Tascam',
        6: 'Teac',
    },
    {
        0: 'U',
        1: 'uCube',
        2: 'Ultralink',
        3: 'Ultrasone',
        4: 'Unison Research',
        5: 'Urbanears',
        6: 'URC',
    },
    {
        0: 'V',
        1: 'V-Moda',
        2: 'VAC',
        3: 'Van Den Hul',
        4: 'Velodyne',
        5: 'Vestax',
        6: 'Vibrapod',
    },
    {
        0: 'W',
        1: 'Wadia',
        2: 'Wharfedale',
        3: 'Whizzer',
        4: 'WHT',
        5: 'Wilson Audio',
        6: 'Wilson-Benesch',
    },
    {
        0: 'X',
        1: 'XLO',
    },
    {
        0: 'Y',
        1: 'Yamaha',
        2: 'Yba',
        3: 'Your Day',
        4: 'YUIN',
        5: 'YuLong',
    },
    {
        0: 'Z',
        1: 'Zappiti',
        2: 'Zesto Audio',
        3: 'Zingali',
        4: 'ZMF',
    },
]